// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPG_Smartify.Data;

namespace RPG_Smartify.Migrations
{
    [DbContext(typeof(RPGdbContext))]
    partial class RPGdbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("RPG_Smartify.Model.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("RPG_Smartify.Model.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RPG_Smartify.Model.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("characterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("characterId")
                        .IsUnique();

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("RPG_Smartify.Model.character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int?>("userid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("userid");

                    b.ToTable("characters");
                });

            modelBuilder.Entity("RPG_Smartify.Model.characterSkill", b =>
                {
                    b.Property<int>("characterId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("characterId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("characterSkills");
                });

            modelBuilder.Entity("RPG_Smartify.Model.Weapon", b =>
                {
                    b.HasOne("RPG_Smartify.Model.character", "character")
                        .WithOne("weapon")
                        .HasForeignKey("RPG_Smartify.Model.Weapon", "characterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("character");
                });

            modelBuilder.Entity("RPG_Smartify.Model.character", b =>
                {
                    b.HasOne("RPG_Smartify.Model.User", "user")
                        .WithMany("Characters")
                        .HasForeignKey("userid");

                    b.Navigation("user");
                });

            modelBuilder.Entity("RPG_Smartify.Model.characterSkill", b =>
                {
                    b.HasOne("RPG_Smartify.Model.Skill", "skill")
                        .WithMany("characterSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPG_Smartify.Model.character", "character")
                        .WithMany("characterSkills")
                        .HasForeignKey("characterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("character");

                    b.Navigation("skill");
                });

            modelBuilder.Entity("RPG_Smartify.Model.Skill", b =>
                {
                    b.Navigation("characterSkills");
                });

            modelBuilder.Entity("RPG_Smartify.Model.User", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("RPG_Smartify.Model.character", b =>
                {
                    b.Navigation("characterSkills");

                    b.Navigation("weapon");
                });
#pragma warning restore 612, 618
        }
    }
}
